### ISSUE TITLE
Support custom display arrangements

### ISSUE THREAD

**Issue by jackmachiela** [matdombrock/MatrixGL#1]
(Related: https://old.reddit.com/r/arduino/comments/mjvmoo/matrixgl_an_arduino_graphics_library_for_led_dot/ )

(project idea: I want to create a photoframe with a Conway's Game Of Life display). I've been wanting to join three MAX7219 4x Dot Matrix Modules into a rectangle of 3x4 modules (or 24x32 LEDs), but in my earlier attempts I could only turn it into a long strip of 1x12 modules (or 8x96 LEDs) - would it be possible to adapt your library to handle that?

**Comment by matdombrock** [comment]
I think this can work. However, right now I'm pretty sure it wont.

One problem is that this library assumes that any additional matrices are adding to the X axis (horizontal). So it's going to want to think of your 3x4 setup as being 1x12. I can think of a few ways to handle that problem but some of this is going to depend on the way that the underlying matrix library handles the addressing of the LEDs. 

I'll need to order a few more LED matrices so I can get a setup like yours that way I can actually test the solutions I'm coming up with. This is something I've actually been thinking about and planning to support since I started writing this library, so thanks for giving me some motivation to keep on it!

I'll update this issue when I think I have a solution in place.

**Comment by jackmachiela** [comment]
I look forward to seeing your progress! Please let me know if there's anything I can do to help, or test.

**Comment by matdombrock** [comment]
@jackmachiela I think I got it working. 

Check out the [new experimental branch](https://github.com/matdombrock/MatrixGL/tree/Experimental). Specifically the [4x2 Example](https://github.com/matdombrock/MatrixGL/blob/Experimental/examples/4x2.ino).

You will need to make sure you are using a [copy of the library from the new experimental branch](https://github.com/matdombrock/MatrixGL/archive/refs/heads/Experimental.zip) to get this to work, but the only real change for the end-user is that you can now add optional arguments (`MDX` & `MDY`) to the library instantiation that allow you to define the amount of displays on your X and Y axes. 

```cpp
MatrixGL(int CLK_PIN, int DATA_PIN, int CS_PIN, int MAX_DEVICES=1, int MDX=NULL, int MDY=NULL);
```

**Wiring Note: You will need to wire the matrices in order from bottom left (being the first) to top right (being the last).**

Once you have it setup like that you can go ahead and start setting points that have a Y value over 7 and the library will automatically handle the addressing abstraction. 

So if you had a 2x2 display setup you could draw 2 points like:
```cpp
matrix.drawPoint(0,0,true);
matrix.drawPoint(15,15,true);
```

This will draw a point in the bottom left corner and another in the top right. The first point is drawn on the first display and the last point is drawn on last display in order of how they are wired.

You can see the new feature working with a simple example in the gif below. 

![md_demo](https://user-images.githubusercontent.com/1508293/115856709-ac61ed00-a3e1-11eb-9e6f-7e67aa227673.gif)

Aside from the flickering issue on the second display (I think thats more of a hardware limitation/problem than anything) I think mostly everything in this library should work as expected in this new branch. 

Let me know if this works for you. I'm excited to see what you build. *I'm also interested to hear what you think about the wiring assumption. Do you think it might make more sense to assume the wiring is from top left to bottom right?*

**Comment by jackmachiela** [comment]
I've just had a quick play with it, and it appears to do exactly what I was after, so thank you for the work you did! What I'm planning on doing with it is a 3x4 matrix (24x32 LEDs), mounted in a photoframe, which should fit almost perfectly, and then run Conway's Game Of Life simulator on it, as a desktoy.

So far I've only run your 4x2 sample, and upgraded it to 4x3, which seems to work as expected. The only issue I had was a broken dupont wire in my inventory, which proved to be a frustrating 25 minutes trying to trace it back before I realised what the problem was.

I think the bottom-left wiring is as good as any other scheme, tbh. It does make more sense from a basic graph point of view, so I'd say leave it as is.

Next I'll implement the Conway code, and will update you as I go.

**Comment by jackmachiela** [comment]
(check your email)

**Comment by matdombrock** [comment]
@jackmachiela glad it worked out for you. 

What's in my email I don't see anything?

**Comment by jackmachiela** [comment]
I tried to send you my project - I'll github it instead (my bad - I emailed it to github notifications by mistake). Will get back to you. In short, It's all working, and my project now just needs a nice frame.

Your library is super easy to use, friend. I've kludged a (messy) version together to do what I'm trying to do, and this week I'll scour the local second-hand shops for a nice looking photoframe. I also implemented a random seed that kicks in if things get too stable, and I was also thinking of adding a LDR that resets the system when I hit it with a laser-pointer from a distance (because laser).

**Comment by jackmachiela** [comment]
https://github.com/jackmachiela/PhotoLife

**Comment by matdombrock** [comment]
@jackmachiela 
That's a really cool project. I've always been interested in learning more about what exactly Conway's Game of Life is. 

This looks like it would be pretty fun to build. I might do a slightly smaller version myself at some point!

Anyways, I merged the experimental branch into master, so this feature is officially part of the library now. 

I also mentioned your project in the readme. 

Thanks again for submitting this issue!

**Comment by jackmachiela** [comment]
Great work, Matthieu! I'll update my project with the live library instead of the experimental one, as soon as I have a minute (halfway through painting the house right now). I'm also busy mounting the hardware into a photoframe, and the project is developing everytime I work on it. You'll see it finish at some point, hopefully. :)

Cheers, and thanks for the shoutout!
